FROM gradle:jdk17-alpine as builder
ARG MODULE
WORKDIR /workspace/app
COPY . /workspace/app/
RUN chmod +x gradlew

RUN ls -la /workspace/app

RUN ./gradlew build -p $MODULE
FROM openjdk:17-ea-17-slim

RUN groupadd -r appuser && useradd -r -g appuser appuser

WORKDIR /app
COPY --from=builder /workspace/app/${MODULE}/build/libs/${MODULE}.jar ./${MODULE}.jar
EXPOSE 8080

USER appuser

ENTRYPOINT ["java","-jar","${MODULE}.jar"]