version: '3'
services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      - wargame_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    image: docker.io/bitnami/kafka:3.3
    networks:
      - wargame_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    networks:
      - wargame_network
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  mysql:
    image: mysql:8.0
    networks:
      - wargame_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=wargame
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  wargame:
    image: wargame:1.0.0
    networks:
      - wargame_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/wargame?serverTimezone=Asia/Seoul
      - SPRING_R2DBC_USERNAME=mysqluser
      - SPRING_R2DBC_PASSWORD=mysqlpw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - MATCHING_TOPIC=matching.users
      - GAME_RESULT_TOPIC=game.result.topic
      - SPRING_DATA_REDIS_HOST=43.201.14.73
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=1116
      - SPRING_REDIS_REACTIVE_ENABLED=true
      - WAITING_VALUE_MAXALLOW=3
      - SCHEDULER_ENABLED=true
      - SPRING_VAR_MATCHEXPIRETIME=3600


#  prometheus:
#    image: prom/prometheus
#    networks:
#      - wargame_network
#    volumes:
#      - ./prometheus/volume:/prometheus
#      - ./prometheus/config:/etc/prometheus
#    ports:
#      - 9090:9090
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    restart: always

#  grafana:
#    image: grafana/grafana
#    networks:
#      - wargame_network
#    volumes:
#      - ./grafana/volume:/var/lib/grafana
#    ports:
#      - 3090:3090
#    restart: always
#    user: root

networks:
  wargame_network:
    driver: bridge