input {
  kafka {
    bootstrap_servers => "kafka:9092" # "kafka-0:9092,kafka-1:9092,kafka-2:9092"
    topics => ["logging.backend.topic", "logging.game.topic"]
    group_id => "logstash-group"
    auto_offset_reset => "earliest"
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "user-behavior-logs"
  }
  stdout { codec => rubydebug }
}