groups:
  - name: HeapUsageAlerts
    rules:
      - alert: HighHeapUsage
        expr: jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"} > 0.8
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Heap Usage High: 80%"
          description: "Heap 사용량이 80% 초과했습니다."

  - name: ThreadBlockingAlerts
    rules:
      - alert: ThreadBlockingRatio
        expr: (jvm_threads_state{state="blocked"} / jvm_threads_count) * 100 > 10
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Blocking Thread:entire ratio 10%"
          description: "쓰레드중 10% 이상 블로킹 상태를 유지하고 있습니다."

      - alert: ThreadBlockingLongDuration
        expr: jvm_threads_state{state="blocked"} > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Blocking Thread:duration 1min"
          description: "쓰레드가 1분 이상 블로킹 상태를 유지하고 있습니다."