global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: "wargame-metrics"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "feed:8080"
          - "match:8081"
          - "membership:8082"
          - "result:8083"
          - "result-query:8084"
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
