name: membership-deployment(Canary)

env:
  MODULE: membership
  BUILD_ID: ${{ github.sha }}
  HELM_BRANCH: dev

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: downfa11/wargame_membership
          IMAGE_TAG: ${{ github.sha }}
        run: |
          envsubst < Dockerfile.template | docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f - .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Checkout Helm Repository
        uses: actions/checkout@v3
        with:
          repository: downfa11/wargame-helm
          path: helm-chart
          ref: main
          ssh-key: ${{ secrets.HELM_CHARTS_REPO_KEY }}

      - name: Update Helm values with new image tag
        run: |
          for chart in membership-chart match-chart result-query-chart result-chart feed-chart; do
            yq -i ".image.tag = \"${{ env.BUILD_ID }}\"" helm-chart/${chart}/values-dev.yaml
          done

      - name: Commit and Push HELM changes
        run: |
          cd helm-chart
          git config --local user.email "downfa11@naver.com"
          git config --local user.name "downfa11"
          git add .
          git commit -m "Update Helm chart for Canary: Module=${{ env.MODULE }}, Tag=${{ env.BUILD_ID }}"
          git push origin ${{ env.HELM_BRANCH }}
